sudo: required
services:
  - docker

before_install:
  - docker build -t ianwang4/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ianwang4/react-test npm test -- --coverage

after_success:
  - docker build -t ianwang4/multi-images-client ./client
  - docker build -t ianwang4/multi-images-nginx ./nginx
  - docker build -t ianwang4/multi-images-server ./server
  - docker build -t ianwang4/multi-images-worker ./worker

  # Login to docker cli 
  