sudo: required
services:
  - docker

before_install:
  - docker build -t ianwang4/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ianwang4/react-test npm test -- --coverage

after_success:
  - docker build -t ianwang4/multi-client ./client
  - docker build -t ianwang4/multi-nginx ./nginx
  - docker build -t ianwang4/multi-server ./server
  - docker build -t ianwang4/multi-worker ./worker

  # Login to docker cli 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # Take these steps and push them to docker hub
  - docker push ianwang4/multi-client 
  - docker push ianwang4/multi-nginx 
  - docker push ianwang4/multi-server 
  - docker push ianwang4/multi-worker 